export const allProducts = [
  {
    id: 1,
    title: 'Men Shirt',
    text: 'Casual cotton shirt',
    img: '/images/Shirt.jpg',
    category: 'Men',
    price: "$70"
  },
  { id: 2, title: 'Men T-shirt', text: 'Graphic tee for summer', img: '/images/Mentshirt1.jpg', category: 'Men', price: "$70" },
  { id: 3, title: 'Men Blazer', text: 'Formal wear', img: '/images/Menblazer.jpg', category: 'Men', price: "$70" },
  { id: 4, title: 'Men Jeans', text: 'Comfortable fit', img: '/images/Mensjeans.jpg', category: 'Men', price: "$70" },
  { id: 5, title: 'Watch', text: 'Elegant and stylish', img: '/images/Menwatch.jpg', category: 'Men', price: "$70" },
  { id: 6, title: 'Sunglasses', text: 'Party wear', img: '/images/Mensunglasses.jpg', category: 'Men', price: "$70" },
  { id: 7, title: 'Caps', text: 'Trendy and sleek', img: '/images/Cap.jpg', category: 'Men', price: "$70" },
  { id: 8, title: 'Belts', text: 'Leather Belt', img: '/images/Belt.jpg', category: 'Men', price: "$70" },
  { id: 9, title: 'Shaving creams', text: 'clean shave', img: '/images/Shavingcream.jpg', category: 'Men', price: "$70" },
  { id: 10, title: 'Oil', text: 'Glowing skin formula', img: '/images/bearedoil.jpg', category: 'Men', price: "$70" },
  { id: 11, title: 'Perfume', text: 'Fresh scent', img: '/images/Perfume.jpg', category: 'Men', price: "$70" },
  { id: 12, title: 'Soap', text: 'Glossy finish', img: '/images/Soap.jpg', category: 'Men', price: "$70" },
  { id: 13, title: 'Sleeper', text: 'regular wear', img: '/images/Sleepers.jpg', category: 'Men', price: "$70" },
  { id: 14, title: 'sports shoes', text: 'Comfortable', img: '/images/Shoes.jpg', category: 'Men', price: "$70" },
  { id: 15, title: 'Boots', text: 'Fancy shoes', img: '/images/Boots.jpg', category: 'Men', price: "$70" },
  { id: 16, title: 'shoes', text: 'party wear', img: '/images/Casualshoes.jpg', category: 'Men', price: "$70" },
  { id: 17, title: 'casual wear', text: 'regular wear', img: '/images/Hoodie.jpg', category: 'Women', price: "$70" },
  { id: 18, title: 'Dresses', text: 'elegant and beautiful', img: '/images/Gown.jpg', category: 'Women', price: "$70" },
  { id: 19, title: 'Sarees', text: 'Soft and Comfortable', img: '/images/Saree1.jpg', category: 'Women', price: "$70" },
  { id: 20, title: 'Lehenga', text: 'Designer fit', img: '/images/Lehenga.jpg', category: 'Women', price: "$70"},
  { id: 21, title: 'Earrings', text: 'Elegant and stylish', img: '/images/Earing.jpg', category: 'Women', price: "$70"},
  { id: 22, title: 'Necklace Set', text: 'Party wear', img: '/images/Necklace.jpg', category: 'Women', price: "$70"},
  { id: 23, title: 'Bangles', text: 'Trendy and sleek', img: '/images/Bangle.jpg', category: 'Women', price: "$70"},
  { id: 24, title: 'Ring', text: 'Minimalist design', img: '/images/Ring.jpg', category: 'Women', price: "$70"},
  { id: 25, title: 'Flats', text: 'Long lasting matte', img: '/images/WomenFlats.jpg', category: 'Women', price: "$70"},
  { id: 26, title: 'Heels', text: 'Glowing skin formula', img: '/images/Heels.jpg', category: 'Women', price: "$70"},
  { id: 27, title: 'Sandals', text: 'Fresh scent', img: '/images/Sandals.jpg', category: 'Women', price: "$70"},
  { id: 28, title: 'Juti', text: 'Glossy finish', img: '/images/Juti.jpg', category: 'Women', price: "$70"},
  { id: 29, title: 'Shirt', text: 'Casual cotton shirt', img: '/images/Kidshirt.jpeg', category: 'Kids', price: "$70"},
  { id: 30, title: 'T-shirt', text: 'Graphic tee for summer', img: '/images/Kidboytshirt.jpg', category: 'Women', price: "$70"},
  { id: 31, title: 'Jeans', text: 'comfortable fit', img: '/images/Kidboyjeans.jpg', category: 'Women', price: "$70"},
  { id: 32, title: 'Shorts', text: 'Comfortable fit', img: '/images/Shorts.jpg', category: 'Women', price: "$70"},
  { id: 33, title: 'Dresses', text: 'Elegant and stylish', img: '/images/babyfrock.jpg', category: 'Women', price: "$70"},
  { id: 34, title: 'Tops', text: 'Party wear', img: '/images/Kidtop.jpg', category: 'Women', price: "$70"},
  { id: 35, title: 'Jeans', text: 'Trendy and sleek', img: '/images/Girljeans.jpg', category: 'Women', price: "$70"},
  { id: 36, title: 'Tshirt', text: 'comfortable fit', img: '/images/Kidtshirt.jpg', category: 'Women', price: "$70"},
  { id: 37, title: 'Soft Toys', text: 'Extra softness', img: '/images/softtoy.jpg', category: 'Women', price: "$70"},
  { id: 38, title: 'Building Toys', text: 'Mega Sized Blocked Toys', img: '/images/Buildingtoy.jpg', category: 'Women', price: "$70"},
  { id: 39, title: 'Educational Toys', text: 'Play and Learn', img: '/images/Educationaltoy.jpg', category: 'Women', price: "$70"},
  { id: 40, title: 'Outdoor Toys', text: 'Quick ride', img: '/images/Outdoortoy.jpg', category: 'Women', price: "$70"},
  { id: 41, title: 'Lipstick', text: 'Matte Lipstick', img: '/images/Lipstic.jpg', category: 'Beauty', price: "$70"},
  { id: 42, title: 'Kajal', text: 'Long lasting', img: '/images/Kajal.jpg', category: 'Beauty', price: "$70" },
  { id: 43, title: 'Nail Polish', text: 'Glossy Finish', img: '/images/Nailpaint.jpg', category: 'Beauty', price: "$70" },
  { id: 44, title: 'Eyelinear', text: 'Waterproof longlasting', img: '/images/Eyelinear.jpg', category: 'Beauty', price: "$70" },
  { id: 45, title: 'Face wash', text: 'Elegant and stylish', img: '/images/Facewash.jpg', category: 'Beauty', price: "$70" },
  { id: 46, title: 'face cream', text: 'Party wear', img: '/images/Facecream.jpg', category: 'Beauty', price: "$70" },
  { id: 47, title: 'Body wash', text: 'Trendy and sleek', img: '/images/Bodywash.jpg', category: 'Beauty', price: "$70" },
  { id: 48, title: 'Body Lotion', text: 'Minimalist design', img: '/images/Bodylotion.jpg', category: 'Beauty', price: "$70" },
  { id: 49, title: 'Shampoo', text: 'Long lasting matte', img: '/images/Shampoo.jpg', category: 'Beauty', price: "$70" },
  { id: 50, title: 'Conditioner', text: 'Glowing skin formula', img: '/images/Conditioner.jpg', category: 'Beauty', price: "$70" },
  { id: 51, title: 'Hair oil', text: 'Fresh scent', img: '/images/Hairoil.jpg', category: 'Beauty', price: "$70" },
  { id: 52, title: 'Hair mask', text: 'Glossy finish', img: '/images/Hairmask.jpg', category: 'Beauty', price: "$70" },
  { id: 53, title: 'Trimmers', text: 'Long lasting matte', img: '/images/Trimmer.jpg', category: 'Beauty', price: "$70" },
  { id: 54, title: 'Beard oil', text: 'Glowing skin formula', img: '/images/bearedoil.jpg', category: 'Beauty', price: "$70" },
  { id: 55, title: 'Soap', text: 'Fresh scent', img: '/images/Soap.jpg', category: 'Beauty', price: "$70" },
  { id: 56, title: 'Shaving cream', text: 'Glossy finish', img: '/images/Shavingcream.jpg', category: 'Beauty', price: "$70" },
  { id: 57, title: 'Earrings', text: 'Elegant and stylish', img: '/images/Earing1.jpg', category: 'Jewelry', price: "$70" },
  { id: 58, title: 'Necklace Set', text: 'Party wear', img: '/images/Necklace1.jpg', category: 'Jewelry', price: "$70" },
  { id: 59, title: 'Bracelet', text: 'Trendy and sleek', img: '/images/Gbracelet.jpg', category: 'Jewelry', price: "$70" },
  { id: 60, title: 'Watch', text: 'Minimalist design', img: '/images/Wwatch.jpg', category: 'Jewelry', price: "$70" },
  { id: 61, title: 'Chains', text: 'Elegant and stylish', img: '/images/Chain.jpg', category: 'Jewelry', price: "$70" },
  { id: 62, title: 'Brooch', text: 'Party wear', img: '/images/Brooch.jpg', category: 'Jewelry', price: "$70" },
  { id: 63, title: 'Bracelet', text: 'Trendy and sleek', img: '/images/Bbracelet.jpg', category: 'Jewelry', price: "$70" },
  { id: 64, title: 'Watches', text: 'Minimalist design', img: '/images/Menwatch.jpg', category: 'Jewelry', price: "$70" },
  { id: 65, title: 'Hair clip', text: 'Fancy and colourful', img: '/images/Hairclip.jpg', category: 'Jewelry', price: "$70" },
  { id: 66, title: 'Hairbands', text: 'Multi-colour fancy', img: '/images/Hairband.jpg', category: 'Jewelry', price: "$70" },
  { id: 67, title: 'Kids Necklace', text: 'Elegant and beautiful', img: '/images/Kidnecklace.jpg', category: 'Jewelry', price: "$70" },
  { id: 68, title: 'Headbands', text: 'fully stretchable ', img: '/images/Headbands.jpg', category: 'Jewelry', price: "$70" },
  
  // ... Add more products with unique `id`s
];
